### ISSUE TITLE
Error occurred while enabling Polymer

### ISSUE THREAD

**Issue by Coloreada** [LinsMinecraftStudio/Polymer#1]
I don't know much about plugins, I'm just going to put what it says in the console, Thanks in advance (server version 1.20.4 paper, host on holyhosting)

Error occurred while enabling Polymer v1.4.7-SNAPSHOT (Is it up to date?)
java.lang.NumberFormatException: For input string: "7-1"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at io.github.linsminecraftstudio.polymer.utils.OtherUtils.isPolymerVersionAtLeast(OtherUtils.java:23) ~[Polymer-1.4.7-SNAPSHOT.jar:?]
        at org.lins.mmmjjkx.polymer.Polymer.lambda$onPlEnable$0(Polymer.java:26) ~[Polymer-1.4.7-SNAPSHOT.jar:?]
        at io.github.linsminecraftstudio.polymer.utils.OtherUtils$Updater.<init>(OtherUtils.java:103) ~[Polymer-1.4.7-SNAPSHOT.jar:?]
        at org.lins.mmmjjkx.polymer.Polymer.onPlEnable(Polymer.java:24) ~[Polymer-1.4.7-SNAPSHOT.jar:?]
        at io.github.linsminecraftstudio.polymer.objects.plugin.PolymerPlugin.onEnable(PolymerPlugin.java:59) ~[Polymer-1.4.7-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by lijinhong11** [comment]
It doesn't support operations

**Comment by lijinhong11** [comment]
Oh well
 needs to improve the fucking updater

**Comment by Coloreada** [comment]
that means?

**Comment by lijinhong11** [comment]
> Oh well needs to improve the fucking updater



> Oh well needs to improve the fucking updater

For temp solution, set checkUpdate to false in config(create it)

**Comment by lijinhong11** [comment]
> that means?

It don't support like 1.0-1 these version strings

**Comment by Coloreada** [comment]
that works, thank you very much for the help
